language: python

python:
  - 3.6

env:
  - DJANGO_VERSION=1.10.8
  - DJANGO_VERSION=1.11.7
  - DJANGO_VERSION=1.11.6
  - DJANGO_VERSION=1.10.8

before_install:
  - export DJANGO_SETTINGS_MODULE=tinyblog.settings
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt
  - pip install -q Django==$DJANGO_VERSION

script:
  - python manage.py makemigrations --noinput
  - python manage.py migrate --noinput
  - coverage run manage.py test --noinput

after_success:
  - coverage report