sudo: required
matrix:
  include:
    - dist: xenial
      sudo: true

env:
  - BLOGGER_IMAGE=abiolarashed/django-tinyblog:$TRAVIS_BUILD_ID

before_install:
  - export DJANGO_SETTINGS_MODULE=tinyblog.settings
  - export PIP_USE_MIRRORS=true

services:
  - docker

before_script:
#  - docker build -t $BLOGGER_IMAGE .
  - docker network create --driver bridge blog-net
  - docker run -d -p 5432:5432 --network=blog-net --name=postgres postgres:latest
  - docker exec -d postgres psql -c 'create database test_db;' -U postgres
#  - docker run -d -p 6379:6379 --network=blog-net --name=redis redis:latest

script:
  - docker ps
#  - docker run -e SECRET_KEY=$SECRET_KEY --network=blog-net --rm -it --name=django-tinyblog $BLOGGER_IMAGE coverage run manage.py test --noinput

#after_success:
#  - coverage report
#  - coveralls
