language: python

python:
  - 3.6

# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
    - python: 3.7.2
      dist: xenial
      sudo: true

env:
  - BLOGGER_IMAGE=abiolarashed/django-tinyblog:$TRAVIS_BUILD_ID
  - NETWORK=${NETWORK}

before_install:
  - export DJANGO_SETTINGS_MODULE=tinyblog.settings
  - export PIP_USE_MIRRORS=true

services:
  - docker

before_script:
  - docker network create --driver bridge ${NETWORK}
  - docker run -d -p 6379:6379 --network=${NETWORK} --name=redis redis:4.0.5-alpine
  - docker run -d -p 5432:5432 --network=${NETWORK} --name=postgres postgres:12-alpine
  - docker exec -d postgres psql -c 'create database test_db;' -U postgres
  - docker build -t ${BLOGGER_IMAGE} .

script:
  - docker run --network=${NETWORK} -itd --name=django-tinyblog ${BLOGGER_IMAGE} coverage run manage.py test --noinput

after_success:
  - coverage report
  - coveralls
