#!/bin/bash
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker push $BLOGGER_IMAGE  # push latest
docker tag $BLOGGER_IMAGE $BASE_IMAGE_NAME:$TRAVIS_TAG
docker push $BASE_IMAGE_NAME:$TRAVIS_TAG
docker logout
