# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.URLField()),
                ('url', models.FilePathField()),
                ('title', models.TextField()),
                ('ip', models.GenericIPAddressField()),
                ('referrer', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('headers', models.TextField()),
                ('session_id', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Page View',
                'verbose_name_plural': 'Page Views',
                'db_table': 'page_view',
                'default_related_name': 'page_view',
            },
        ),
    ]
