apiVersion: v1
appVersion: "1.0"
description: A Helm chart for Kubernetes
name: django-tinyblog-chart
version: 0.1.0
keywords:
  - django-tinyblog
  - django
  - tinyblog
  - blog
home: https://github.com/abiolarasheed/django-tinyblog
sources:
  - https://github.com/abiolarasheed/django-tinyblog
