# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("blog", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="slug",
            field=models.SlugField(editable=False, max_length=140, unique=True),
        )
    ]
