# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 12:06
from __future__ import unicode_literals

import blog.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("blog", "0002_auto_20171029_1756")]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="poster",
            field=models.ImageField(
                blank=True, null=True, upload_to=blog.utils.FileUploader()
            ),
        )
    ]
