# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20171105_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='views',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
