apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: django-tinyblog-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  tls:
  - hosts:
    - "{{ $.Values.domain_name }}"
    secretName: {{ $.Values.tls.secretName }}
  rules:
  - host: "{{ $.Values.domain_name }}"
    http:
      paths:
      - backend:
          serviceName: django-tinyblog
          servicePort: 8000
        path: /(.*)

  - host: "{{ $.Values.domain_name }}"
    http:
      paths:
      - backend:
          serviceName: django-tinyblog
          servicePort: 8000
        path: /(.*)