apiVersion: v1
kind: Secret
metadata:
  name: secrets
  annotations:
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
data:
  {{- range $key, $val := $.Values.secrets.data }}
        {{ $key | indent 6}}: {{ $val }}
  {{- end}}
