---
apiVersion: v1
kind: Service
metadata:
  name: django-tinyblog
  labels:
    chart: {{ template "django-tinyblog.fullname" . }}-django-web-app
spec:
  selector:
    chart: {{ template "django-tinyblog.fullname" . }}-django-web-app
  ports:
    - name: http
      port: 9090
      targetPort: 9090
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    chart: {{ template "django-tinyblog.fullname" . }}-redis
spec:
  selector:
    chart: {{ template "django-tinyblog.fullname" . }}-redis
  ports:
    - name: http
      port: 6379
      targetPort: 6379
  type: ClusterIP
